#!/usr/bin/env python3
import os
import sys
import re
from typing import Optional
import subprocess
import threading
import tkinter as tk
from tkinter import filedialog, messagebox
# no combobox, C++ only suggestion/highlighting


class CppEditorApp:
    def __init__(self, root):
        self.root = root
        self.root.title('C++ Editor & Compiler')
        self.current_file = None
        self._build_ui()
        self._bind_events()
        # Start with an example C++ snippet
        # Initialize highlight_timer before calling update_highlight in set_text
        self.highlight_timer = None
        # process management
        self.current_process: Optional[subprocess.Popen] = None
        # track exe path generated by last compile (may be temp or persistent)
        self.current_exe: Optional[str] = None
        # track temporary files we need to cleanup
        self._temp_files: list[str] = []
        # track last temporary source file (for error mapping)
        self._last_temp_source: Optional[str] = None
        # aggressive cleanup policy: keep only N recent temp files
        self._temp_keep_last = 1
        # track if editor buffer is modified (unsaved changes)
        self.dirty = False
        # autocomplete/suggestion timers and UI
        self.autocomplete_timer = None
        self.diagnostic_timer = None
        # Use the module-level Optional to keep typing style consistent
        self.suggest_box: Optional[tk.Toplevel] = None
        self.suggest_list: Optional[tk.Listbox] = None
        self.suggest_start: Optional[str] = None
        self.suggest_end: Optional[str] = None
        self.set_text(self.default_cpp())
        self.update_highlight()

    def _build_ui(self):
        menubar = tk.Menu(self.root)
        filemenu = tk.Menu(menubar, tearoff=False)
        filemenu.add_command(label='New', command=self.new_file)
        filemenu.add_command(label='Open', command=self.open_file)
        filemenu.add_command(label='Save', command=self.save_file)
        filemenu.add_command(label='Save As', command=self.save_file_as)
        filemenu.add_separator()
        filemenu.add_command(label='Exit', command=self.root.quit)
        menubar.add_cascade(label='File', menu=filemenu)

        buildmenu = tk.Menu(menubar, tearoff=False)
        buildmenu.add_command(label='Compile', command=self.compile_code)
        buildmenu.add_command(label='Run', command=self.run_program)
        buildmenu.add_command(label='Compile & Run', command=self.compile_and_run)
        menubar.add_cascade(label='Build', menu=buildmenu)

        self.root.config(menu=menubar)

        # Top frame: code editor with line numbers
        top_frame = tk.Frame(self.root)
        top_frame.pack(fill='both', expand=True)

        self.line_numbers = tk.Text(top_frame, width=5, padx=3, takefocus=0, bd=0, bg='#f0f0f0', fg='gray', state='disabled')
        self.line_numbers.pack(side='left', fill='y')

        self.text = tk.Text(top_frame, wrap='none', undo=True, font=('Consolas', 12))
        self.text.pack(side='left', fill='both', expand=True)

        xscroll = tk.Scrollbar(self.root, orient='horizontal', command=self.text.xview)
        xscroll.pack(fill='x')
        self.text.configure(xscrollcommand=xscroll.set)

        side_frame = tk.Frame(self.root)
        side_frame.pack(fill='x')
        btn_compile = tk.Button(side_frame, text='Compile', command=self.compile_code)
        btn_compile.pack(side='left', padx=6, pady=6)
        btn_run = tk.Button(side_frame, text='Run', command=self.run_program)
        btn_run.pack(side='left', padx=6, pady=6)
        btn_crun = tk.Button(side_frame, text='Compile && Run', command=self.compile_and_run)
        btn_crun.pack(side='left', padx=6, pady=6)
        btn_stop = tk.Button(side_frame, text='Stop', command=self.stop_current_process)
        btn_stop.pack(side='left', padx=6, pady=6)

        # C++ only highlighting (no language selector)

        self.status_var = tk.StringVar()
        self.status_var.set('Ready')
        status = tk.Label(self.root, textvariable=self.status_var, relief='sunken', anchor='w')
        status.pack(side='bottom', fill='x')

        # Output console
        self.output = tk.Text(self.root, height=12, bg='#111111', fg='#ffffff', font=('Consolas', 11))
        self.output.pack(fill='both')
        self.output.insert('end', 'Output console available.\n')
        self.output.configure(state='disabled')

        # Syntax highlight tags (base config)
        self.text.tag_configure('error_line', background='#420000')

        # Try to use external SyntaxHighlighter (Pygments) if available
        try:
            import syntax_highlighter as sh
            if getattr(sh, 'PYGMENTS_AVAILABLE', False):
                from syntax_highlighter import SyntaxHighlighter
                self.highlighter = SyntaxHighlighter(self.text)
                self.highlighter.create_tags()
            else:
                self.highlighter = None
        except Exception:
            self.highlighter = None
        # Basic tags fallback if no Pygments-based highlighter
        if not self.highlighter:
            self.text.tag_configure('keyword', foreground='blue')
            self.text.tag_configure('type', foreground='#1c9d00')
            self.text.tag_configure('string', foreground='#d14')
            self.text.tag_configure('comment', foreground='#888')

    def _bind_events(self):
        # Bind key events to set dirty flag, update highlights, and show suggestions
        self.text.bind('<KeyRelease>', self._on_key_release)
        self.text.bind('<Tab>', self._on_tab)
        self.text.bind('<FocusOut>', lambda e: self._hide_suggestions())
        self.text.bind('<Button-1>', lambda e: self.update_line_numbers())
        self.text.bind('<MouseWheel>', lambda e: self.update_line_numbers())
        self.text.bind('<Return>', lambda e: self.update_line_numbers())
        # No language combobox: always use C++ highlighting

        # Bind close event to check for unsaved changes
        self.root.protocol('WM_DELETE_WINDOW', self.on_close)

    def default_cpp(self):
        return r"""#include <iostream>
using namespace std;

int main() {
    cout << "Hello, World!" << endl;
    return 0;
}
"""

    def new_file(self):
        if not self.confirm_discard():
            return
        self.current_file = None
        self.set_text('')
        self.status_var.set('New file')

    def confirm_discard(self):
        # Ask user to confirm if there are unsaved changes
        if not self.dirty:
            return True
        resp = messagebox.askyesnocancel('Unsaved changes', 'You have unsaved changes. Save before continuing?')
        if resp is None:
            # cancel
            return False
        if resp is True:
            return self.save_file()
        # resp is False -> discard
        return True

    def set_dirty(self, v: bool):
        self.dirty = v
        # also set Tk edit modified flag for compatibility
        try:
            self.text.edit_modified(bool(v))
        except Exception:
            pass

    def open_file(self):
        path = filedialog.askopenfilename(title='Open C++ file', filetypes=[('C++ Files', '*.cpp *.hpp *.h *.cc *.c'), ('All Files', '*.*')])
        if path:
            with open(path, 'r', encoding='utf-8', errors='ignore') as f:
                self.set_text(f.read())
            self.current_file = path
            self.status_var.set(f'Opened {os.path.basename(path)}')
            self.set_dirty(False)

    def save_file(self):
        if self.current_file is None:
            return self.save_file_as()
        text = self.get_text()
        with open(self.current_file, 'w', encoding='utf-8') as f:
            f.write(text)
        self.status_var.set(f'Saved {os.path.basename(self.current_file)}')
        self.set_dirty(False)
        return True

    def save_file_as(self):
        path = filedialog.asksaveasfilename(defaultextension='.cpp', filetypes=[('C++ Files', '*.cpp *.hpp *.h *.cc *.c'), ('All Files', '*.*')])
        if not path:
            return False
        self.current_file = path
        return self.save_file()

    def set_text(self, txt):
        self.text.delete('1.0', 'end')
        self.text.insert('1.0', txt)
        self.update_line_numbers()
        self.update_highlight()
        # Reset dirty flag when setting text programmatically
        self.set_dirty(False)

    def get_text(self):
        return self.text.get('1.0', 'end-1c')

    def update_line_numbers(self):
        content = self.get_text().splitlines()
        width = len(str(max(1, len(content))))
        self.line_numbers.config(state='normal')
        self.line_numbers.delete('1.0', 'end')
        for i in range(1, len(content) + 1):
            self.line_numbers.insert('end', f'{i}'.rjust(width) + '\n')
        self.line_numbers.config(state='disabled')

    def update_highlight(self):
        if self.highlight_timer:
            self.root.after_cancel(self.highlight_timer)
        self.highlight_timer = self.root.after(80, self._highlight)

    def _highlight(self):
        # Use external Pygments-based SyntaxHighlighter if available
        if self.highlighter:
            # make sure prior tags are cleared by highlighter
            lang = 'cpp'
            try:
                # Prefer highlighting visible region for performance
                self.highlighter.highlight_visible_region(language=lang)
            except Exception:
                self.highlighter.highlight_all(language=lang)
            return

        # Fallback: basic regex highlight
        text = self.get_text()
        self.text.tag_remove('keyword', '1.0', 'end')
        self.text.tag_remove('type', '1.0', 'end')
        self.text.tag_remove('string', '1.0', 'end')
        self.text.tag_remove('comment', '1.0', 'end')
        # Basic highlights
        keywords = r'\b(if|else|for|while|return|break|continue|goto|switch|case|default|namespace|using|class|struct|template|typename|public|private|protected|virtual|override|constexpr)\b'
        types = r'\b(int|long|short|float|double|char|void|bool|unsigned|signed|size_t|auto)\b'
        for m in re.finditer(keywords, text):
            start = f'1.0+{m.start()}c'
            end = f'1.0+{m.end()}c'
            self.text.tag_add('keyword', start, end)
        for m in re.finditer(types, text):
            start = f'1.0+{m.start()}c'
            end = f'1.0+{m.end()}c'
            self.text.tag_add('type', start, end)
        # strings
        for m in re.finditer(r'(".*?"|\'.*?\')', text):
            start = f'1.0+{m.start()}c'
            end = f'1.0+{m.end()}c'
            self.text.tag_add('string', start, end)
        # comments // and /* */
        for m in re.finditer(r'//.*', text):
            start = f'1.0+{m.start()}c'
            end = f'1.0+{m.end()}c'
            self.text.tag_add('comment', start, end)
        for m in re.finditer(r'/\*.*?\*/', text, flags=re.DOTALL):
            start = f'1.0+{m.start()}c'
            end = f'1.0+{m.end()}c'
            self.text.tag_add('comment', start, end)

    def compile_code(self):
        # Compile current editor text without requiring the user to save
        path, is_temp = self._prepare_source_for_compile()
        if not path:
            messagebox.showerror('Error', 'Unable to prepare source for compilation')
            return
        self.output_clear()
        self.status_var.set('Compiling...')
        threading.Thread(target=self._compile_thread, args=(path, is_temp), daemon=True).start()

    def _compile_thread(self, path, is_temp: bool):
        base, ext = os.path.splitext(path)
        out_exe = base  # without extension; on Linux, no .exe
        cmd = ['g++', '-std=c++17', path, '-o', out_exe]
        try:
            proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            self.current_process = proc
            try:
                stdout, stderr = proc.communicate()
            finally:
                self.current_process = None
        except Exception as e:
            self.output_write(f'Error running g++: {e}\n')
            self.status_var.set('Compilation failed')
            return
        if proc.returncode != 0:
            self.output_write('Compiler returned errors:\n', clear=False)
            self.output_write(stderr)
            self.status_var.set('Compilation failed')
            self._parse_and_highlight_errors(stderr)
        else:
            self.output_write('Compilation succeeded.\n')
            self.status_var.set('Compiled')
            # set the current_exe path so run_program can run the latest build
            self.current_exe = out_exe
            # register the temp exe for cleanup
            try:
                if is_temp:
                    try:
                        self._temp_files.append(out_exe)
                    except Exception:
                        pass
            except Exception:
                pass
            # if the source was a temporary file, we can remove the source now
            if is_temp:
                try:
                    os.unlink(path)
                except Exception:
                    pass

    def _parse_and_highlight_errors(self, stderr_text):
        # Parse messages like: file.cpp:line:col: error: message
        # Simplify: highlight line numbers in the current editor
        for tag in ('error_line',):
            self.text.tag_remove(tag, '1.0', 'end')
        pattern = re.compile(r'(?P<file>[^:\s]+):(\s?)(?P<line>\d+):(\d+):\s(?P<kind>error|warning):\s(?P<msg>.*)')
        for m in pattern.finditer(stderr_text):
            file = m.group('file')
            line = int(m.group('line'))
            match_current = False
            try:
                if self.current_file and os.path.basename(self.current_file) == os.path.basename(file):
                    match_current = True
                elif self._last_temp_source and os.path.basename(self._last_temp_source) == os.path.basename(file):
                    match_current = True
            except Exception:
                match_current = False
            if match_current:
                # highlight this line
                start = f'{line}.0'
                end = f'{line}.0 + 1 line'
                self.text.tag_add('error_line', start, end)
                # Make sure to scroll to the first error
                try:
                    self.text.see(start)
                except Exception:
                    pass

    def run_program(self):
        # Prefer executing the last compiled exe (may be temporary)
        exe = self.current_exe
        if exe is None or not os.path.exists(exe):
            # fallback: try to compile current content on-the-fly and run
            path, is_temp = self._prepare_source_for_compile()
            if not path:
                messagebox.showerror('Error', 'Executable not found. Compile first.')
                return
            # compile then run using compile_and_run thread
            self.compile_and_run()
            return
        self.output_clear()
        self.status_var.set('Running...')
        threading.Thread(target=self._run_thread, args=(exe,), daemon=True).start()

    def _run_thread(self, exe):
        try:
            proc = subprocess.Popen([exe], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            self.current_process = proc
            try:
                stdout, stderr = proc.communicate(timeout=20)
            except subprocess.TimeoutExpired:
                proc.kill()
                stdout, stderr = proc.communicate()
                self.current_process = None
                self.output_write('\nProgram timed out (20s).\n')
                self.status_var.set('Program timed out')
                return
            self.current_process = None
        except subprocess.TimeoutExpired:
            self.output_write('\nProgram timed out (20s).\n')
            self.status_var.set('Program timed out')
            return
        except Exception as e:
            self.output_write(f'Error running program: {e}\n')
            self.status_var.set('Run failed')
            return
        if stdout:
            self.output_write(stdout)
        if stderr:
            self.output_write(stderr)
        try:
            retcode = proc.returncode
        except Exception:
            retcode = 0
        self.status_var.set(f'Execution finished (code {retcode})')

    def compile_and_run(self):
        path, is_temp = self._prepare_source_for_compile()
        if not path:
            messagebox.showerror('Error', 'Unable to prepare source for compilation')
            return
        self.output_clear()
        self.status_var.set('Compiling and running...')
        threading.Thread(target=self._compile_and_run_thread, args=(path, is_temp), daemon=True).start()

    def _compile_and_run_thread(self, path, is_temp: bool):
        base, ext = os.path.splitext(path)
        exe = base
        cmd = ['g++', '-std=c++17', path, '-o', exe]
        try:
            proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            self.current_process = proc
            try:
                stdout, stderr = proc.communicate()
            finally:
                self.current_process = None
        except Exception as e:
            self.output_write(f'Error running g++: {e}\n')
            self.status_var.set('Compilation failed')
            return
        if proc.returncode != 0:
            self.output_write('Compilation failed:\n')
            self.output_write(stderr)
            self.status_var.set('Compilation failed')
            self._parse_and_highlight_errors(stderr)
            return
        self.output_write('Compilation succeeded. Running...\n')
        try:
            runproc = subprocess.Popen([exe], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            self.current_process = runproc
            try:
                out, err = runproc.communicate(timeout=20)
            except subprocess.TimeoutExpired:
                runproc.kill()
                out, err = runproc.communicate()
                self.current_process = None
                self.output_write('\nProgram timed out (20s).\n')
                self.status_var.set('Program timed out')
                return
            # normal completion path
            self.current_process = None
            # record latest exe
            self.current_exe = exe
            if is_temp:
                try:
                    self._temp_files.append(exe)
                except Exception:
                    pass
            # cleanup source if it was temporary
            if is_temp:
                try:
                    os.unlink(path)
                except Exception:
                    pass
        except subprocess.TimeoutExpired:
            self.output_write('\nProgram timed out (20s).\n')
            self.status_var.set('Program timed out')
            return
        except Exception as e:
            self.output_write(f'Error running program: {e}\n')
            self.status_var.set('Run failed')
            return
        if out:
            self.output_write(out)
        if err:
            self.output_write(err)
        try:
            ret = runproc.returncode
        except Exception:
            ret = 0
        self.status_var.set(f'Execution finished (code {ret})')

    # ------------------ inline suggestions / autocomplete ------------------
    def _on_key_release(self, event):
        # Set dirty flag
        self.set_dirty(True)
        # Re-highlight current line immediately for as-you-type feedback
        if self.highlighter:
            try:
                lineno = int(str(self.text.index('insert')).split('.')[0])
                lang = 'cpp'
                self.highlighter.highlight_line(lineno, language=lang)
            except Exception:
                # Fallback: refresh visible region
                self.update_highlight()
        else:
            # fallback: update full or line-level regex
            self.update_highlight()

        # Trigger suggestions for identifiers
        self._schedule_autocomplete()
        # run quick diagnostics
        self._schedule_quick_diagnostics()

    def _schedule_quick_diagnostics(self):
        if getattr(self, 'diagnostic_timer', None):
            self.root.after_cancel(self.diagnostic_timer)
        self.diagnostic_timer = self.root.after(120, self._diagnose_current_line)

    def _diagnose_current_line(self):
        # Clear previous error tags for now
        self.text.tag_remove('error_line', '1.0', 'end')
        # Visible region check for unmatched braces/quotes and missing semicolons
        try:
            first_idx = self.text.index('@0,0')
            last_idx = self.text.index(f'@0,{self.text.winfo_height()}')
            full_text = self.text.get('1.0', 'end-1c')
        except Exception:
            full_text = self.text.get('1.0', 'end-1c')
            first_idx = '1.0'
            last_idx = 'end'

        # We'll run a lightweight scan on the visible region lines
        try:
            first_line = int(first_idx.split('.')[0])
            last_line = int(last_idx.split('.')[0])
        except Exception:
            first_line = 1
            last_line = max(1, full_text.count('\n') + 1)

        lines = full_text.splitlines()
        # Bracket stack to detect mismatches in visible region
        stack = []
        for i in range(first_line - 1, min(last_line, len(lines))):
            line = lines[i]
            for ch in line:
                if ch in '{([':
                    stack.append((ch, i + 1))
                elif ch in '})]':
                    if stack:
                        top, tline = stack[-1]
                        if (top == '{' and ch == '}') or (top == '(' and ch == ')') or (top == '[' and ch == ']'):
                            stack.pop()
                        else:
                            # mismatch: highlight this line
                            start = f'{i + 1}.0'
                            end = f'{i + 1}.0 + 1 line'
                            self.text.tag_add('error_line', start, end)
                            # also scroll to it
                            self.text.see(start)
                    else:
                        # unmatched closing
                        start = f'{i + 1}.0'
                        end = f'{i + 1}.0 + 1 line'
                        self.text.tag_add('error_line', start, end)
                        self.text.see(start)
        # Any remaining opening brackets in stack -> mark their lines
        for _, line_no in stack:
            start = f'{line_no}.0'
            end = f'{line_no}.0 + 1 line'
            self.text.tag_add('error_line', start, end)
            self.text.see(start)

        # Missing semicolon suggestion: naive: if previous line ends with expression and no ;
        try:
            cur_line = int(self.text.index('insert').split('.')[0])
            if cur_line - 1 >= 1:
                prev_line_text = lines[cur_line - 2].rstrip()
                if prev_line_text and not prev_line_text.endswith(';') and not prev_line_text.endswith('{') and not prev_line_text.startswith('#') and not prev_line_text.strip().startswith('//') and not prev_line_text.endswith('}'):
                    # Suggest semicolon by putting a suggestion in the suggestions box
                    hint = 'Add ;'
                    # show in suggestion list for quickfix
                    self._show_quickfix_hint(hint, cur_line - 1)
        except Exception:
            pass

    def _show_quickfix_hint(self, hint_text: str, line_no: int):
        # add quick fix suggestion as special item in suggestions if none present
        items = [hint_text]
        # compute end of line
        try:
            line_text = self.text.get(f'{line_no}.0', f'{line_no}.end')
            end_index = f"{line_no}.{len(line_text)}"
        except Exception:
            end_index = f'{line_no}.end'
        # show suggestion at the end of the line
        self._show_suggestion_box(items, end_index, end_index)

    def _prepare_source_for_compile(self):
        """Write current editor content to a temp file and return (path, is_temp).
        If the editor is tied to a saved file and matches on disk, we still compile the current
        content by writing to a temporary file so we don't require a save."""
        txt = self.get_text()
        # Clean up older temp files first, keep only last N
        try:
            self._cleanup_temp_files(keep_last=self._temp_keep_last)
        except Exception:
            pass
        try:
            # Create a named temp source file
            import tempfile as _tempfile
            tf = _tempfile.NamedTemporaryFile(delete=False, suffix='.cpp', prefix='scc_', mode='w', encoding='utf-8')
            tf.write(txt)
            tf.flush()
            tf.close()
            # ensure we remove prior temp exes if any
            # track temp file for cleanup on exit
            self._temp_files.append(tf.name)
            self._last_temp_source = tf.name
            return tf.name, True
        except Exception:
            return None, False

    def _cleanup_temp_files(self, keep_last: int = 1):
        """Remove old temporary files, keeping only the last `keep_last` entries in the
        `_temp_files` list. This prevents disk accumulation by removing older temporary
        sources and executables created during compile operations.
        """
        if not getattr(self, '_temp_files', None):
            return
        try:
            if keep_last < 0:
                keep_last = 0
            # Determine which files to remove
            if keep_last == 0:
                to_remove = list(self._temp_files)
            else:
                to_remove = list(self._temp_files[:-keep_last])
            for p in to_remove:
                try:
                    if p and os.path.exists(p):
                        os.unlink(p)
                except Exception:
                    pass
            # retain only the most recent `keep_last` items
            if keep_last == 0:
                self._temp_files = []
            else:
                self._temp_files = self._temp_files[-keep_last:]
            # Also ensure _last_temp_source is consistent
            if self._temp_files:
                # prefer latest source if present among kept files
                last_source = None
                for p in reversed(self._temp_files):
                    if p and p.endswith('.cpp'):
                        last_source = p
                        break
                self._last_temp_source = last_source
            else:
                self._last_temp_source = None
        except Exception:
            pass

    def _schedule_autocomplete(self):
        if getattr(self, 'autocomplete_timer', None):
            self.root.after_cancel(self.autocomplete_timer)
        self.autocomplete_timer = self.root.after(160, self._show_autocomplete)

    def _show_autocomplete(self):
        # find the current word under the caret
        # Only show suggestions for C++ files (based on extension), otherwise hide
        if self.current_file:
            _, ext = os.path.splitext(self.current_file)
            if ext.lower() not in ('.cpp', '.cc', '.cxx', '.c', '.hpp', '.hh', '.h', '.hxx'):
                self._hide_suggestions()
                return
        # find the current word under the caret using direct scanning
        text = self.get_text()
        cur = self.text.index('insert')
        try:
            line, col = map(int, cur.split('.'))
        except Exception:
            self._hide_suggestions()
            return
        lines = text.splitlines(True)
        if line - 1 >= len(lines):
            self._hide_suggestions()
            return
        # compute absolute char offset
        start_offset = sum(len(s) for s in lines[:line - 1])
        abs_idx = start_offset + col
        # scan left to find start of identifier
        left = abs_idx
        while left > 0 and (text[left - 1].isalnum() or text[left - 1] == '_'):
            left -= 1
        right = abs_idx
        while right < len(text) and (text[right].isalnum() or text[right] == '_'):
            right += 1
        if left == abs_idx:
            self._hide_suggestions()
            return
        # convert back to index strings
        word_start = f'{line}.{left - start_offset}'
        word_end = f'{line}.{col}'
        prefix = text[left:abs_idx]
        if not prefix or len(prefix) < 1:
            self._hide_suggestions()
            return
        # compute suggestions: keywords + names in file
        suggestions = self._collect_suggestions(prefix)
        if not suggestions:
            self._hide_suggestions()
            return
        # show suggestion popup
        self._show_suggestion_box(suggestions, word_start, word_end)

    def _collect_suggestions(self, prefix: str):
        pref = prefix
        # C++ keywords + common std names
        base_keywords = [
            'int', 'long', 'short', 'char', 'bool', 'double', 'float', 'auto', 'void', 'return', 'if', 'else', 'for', 'while', 'switch', 'case', 'default', 'break', 'continue', 'namespace', 'using', 'std', 'cout', 'cin', 'vector', 'string', 'map', 'unordered_map', 'set', 'unordered_set', 'list', 'deque', 'queue', 'stack', 'pair', 'tuple', 'algorithm', 'sort', 'find', 'endl', 'nullptr', 'new', 'delete', 'class', 'struct', 'template', 'typename', 'public', 'private', 'protected', 'virtual', 'override', 'const', 'static', 'constexpr', 'include', 'iostream', 'fstream', 'sstream'
        ]
        # gather file symbols
        text = self.get_text()
        symbols = set(re.findall(r"\b([A-Za-z_][A-Za-z0-9_]*)\b", text))
        candidates = set(base_keywords) | symbols
        # Filter
        filtered = [s for s in sorted(candidates) if s.startswith(pref) and s != pref]
        # Limit suggestions number
        return filtered[:30]

    def _show_suggestion_box(self, suggestions, start, end):
        # create Toplevel once
        if self.suggest_box is None:
            self.suggest_box = tk.Toplevel(self.root)
            self.suggest_box.wm_overrideredirect(True)
            self.suggest_list = tk.Listbox(self.suggest_box, height=6)
            self.suggest_list.pack(side='left', fill='both', expand=True)
            self.suggest_list.bind('<Double-1>', lambda e: self._accept_suggestion())
            self.suggest_list.bind('<Return>', lambda e: self._accept_suggestion())
            self.suggest_list.bind('<Escape>', lambda e: self._hide_suggestions())
            self.suggest_list.bind('<Up>', self._suggest_up)
            self.suggest_list.bind('<Down>', self._suggest_down)
        else:
            # clear
            if self.suggest_list is not None:
                self.suggest_list.delete(0, 'end')
        # populate
        if self.suggest_list is not None:
            for item in suggestions:
                self.suggest_list.insert('end', item)
        # select first
        if self.suggest_list is not None:
            self.suggest_list.select_set(0)
        # position near caret
        try:
            bbox = self.text.bbox('insert')
            if bbox:
                x, y, width, height = bbox
                x = x + self.text.winfo_rootx()
                y = y + self.text.winfo_rooty() + height
            else:
                x = self.text.winfo_rootx()
                y = self.text.winfo_rooty()
        except Exception:
            x = self.text.winfo_rootx()
            y = self.text.winfo_rooty()
        if self.suggest_box is not None:
            self.suggest_box.wm_geometry(f'+{x}+{y}')
            self.suggest_box.deiconify()
            self.suggest_box.lift()
            self.suggest_box.update_idletasks()
        self.suggest_start = start
        self.suggest_end = end
        # Focus list to receive keys
        try:
            if self.suggest_list is not None:
                self.suggest_list.focus_set()
        except Exception:
            pass

    def _hide_suggestions(self):
        if self.suggest_box is not None:
            try:
                self.suggest_box.withdraw()
            except Exception:
                pass
        try:
            # Return focus to editor
            self.text.focus_set()
        except Exception:
            pass

    def _suggest_up(self, event):
        try:
            sl = self.suggest_list
            if sl is None:
                return 'break'
            cur = sl.curselection()[0]
            if cur > 0:
                sl.select_clear(cur)
                sl.select_set(cur - 1)
                sl.activate(cur - 1)
        except Exception:
            pass
        return 'break'

    def _suggest_down(self, event):
        try:
            sl = self.suggest_list
            if sl is None:
                return 'break'
            cur = sl.curselection()[0]
            if cur < sl.size() - 1:
                sl.select_clear(cur)
                sl.select_set(cur + 1)
                sl.activate(cur + 1)
        except Exception:
            pass
        return 'break'

    def _on_tab(self, event):
        # If suggestion box visible, accept suggestion, otherwise insert tab
        try:
            if self.suggest_box is not None and getattr(self.suggest_box, 'winfo_viewable', lambda: False)():
                self._accept_suggestion()
                return 'break'
        except Exception:
            pass
        try:
            self.text.insert('insert', '\t')
        except Exception:
            pass
        return 'break'

    def _accept_suggestion(self):
        try:
            sl = self.suggest_list
            if sl is None:
                return
            sel = sl.curselection()
            if not sel:
                return
            value = sl.get(sel[0])
            # replace the suggested word in the editor
            try:
                # If quickfix hint such as 'Add ;' replace special behavior
                if isinstance(value, str) and value.startswith('Add ;'):
                    # Insert a semicolon at suggest_start (usually end of line)
                    try:
                        if self.suggest_start is not None:
                            self.text.insert(self.suggest_start, ';')
                        else:
                            self.text.insert('insert', ';')
                    except Exception:
                        # fallback: insert at cursor
                        self.text.insert('insert', ';')
                else:
                    if self.suggest_start is not None and self.suggest_end is not None:
                        self.text.delete(self.suggest_start, self.suggest_end)
                        self.text.insert(self.suggest_start, value)
                        # move caret to end of inserted value
                        new_index = f"{self.suggest_start}+{len(value)}c"
                        self.text.mark_set('insert', new_index)
                    else:
                        # fallback: just insert at cursor
                        self.text.insert('insert', value)
            except Exception:
                pass
            self._hide_suggestions()
            self.set_dirty(True)
            self.update_highlight()
        except Exception:
            pass

    def stop_current_process(self):
        proc = getattr(self, 'current_process', None)
        if proc is not None:
            try:
                proc.kill()
                self.output_write('\nProcess killed by user.\n')
                self.status_var.set('Stopped')
                self.current_process = None
            except Exception:
                pass

    def on_close(self):
        if self.confirm_discard():
            # Good to close
            # Cleanup any temp files we created during runtime
            for p in getattr(self, '_temp_files', []):
                try:
                    if p and os.path.exists(p):
                        os.unlink(p)
                except Exception:
                    pass
            try:
                self.root.destroy()
            except Exception:
                self.root.quit()

    def output_write(self, text, clear=False):
        def _write():
            if clear:
                self.output.config(state='normal')
                self.output.delete('1.0', 'end')
                self.output.config(state='disabled')
            self.output.config(state='normal')
            self.output.insert('end', text)
            self.output.see('end')
            self.output.config(state='disabled')
        self.root.after(0, _write)

    def output_clear(self):
        self.root.after(0, lambda: (self.output.config(state='normal'), self.output.delete('1.0', 'end'), self.output.config(state='disabled')))


def _ensure_venv():
    """Restart the script in the .venv if it exists and we're not already in it."""
    venv_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".venv")
    if not os.path.exists(venv_dir):
        return

    # Check if we are running from the venv
    if sys.platform == "win32":
        python_exe = os.path.join(venv_dir, "Scripts", "python.exe")
    else:
        python_exe = os.path.join(venv_dir, "bin", "python")

    # If the venv python doesn't exist, we can't switch
    if not os.path.exists(python_exe):
        return

    # If we are already running the venv python, do nothing
    if os.path.abspath(sys.executable) == os.path.abspath(python_exe):
        return

    print(f"Switching to virtual environment: {venv_dir}...")
    try:
        os.execv(python_exe, [python_exe] + sys.argv)
    except OSError as e:
        print(f"Failed to switch to venv: {e}")


def main():
    root = tk.Tk()
    CppEditorApp(root)
    root.minsize(640, 480)
    root.mainloop()


if __name__ == '__main__':
    _ensure_venv()
    main()
